apiVersion: v1
kind: ConfigMap
metadata:
  name: wmregistry-config
#common configuration shared between all applications
data:
  application.yml: |-
    configserver:
      name:  JHipster Registry
      status: Connected to the JHipster Registry running in Kubernetes
    eureka:
      client:
        initial-instance-info-replication-interval-seconds: 15
        instance-info-replication-interval-seconds: 15
        registry-fetch-interval-seconds: 15
        fetch-registry: true
        register-with-eureka: true
        eureka-service-url-poll-interval-seconds: 15
      instance:
        lease-renewal-interval-in-seconds: 10
        registry-default-open-for-traffic-count: 0
    jhipster:
      security:
        authentication:
          jwt:
            base64-secret: OWEzYWQ0ODdkMjUxNDJjYTFiNmI3ZWE4OGVlNDM4NmRlY2U4ZGFlNmEwNWQ3ZTY1ZGU0YzhkZTdjOTZkZTQzOTVhMjFlZWRhZGFmY2JiZTk4MGM0ZDcwODBkYjUxNDI4NzMzZQ==
  # app specific configuration
  wm-registry.yml: |-
    eureka:
      client:
        service-url:
          defaultZone: http://admin:${spring.security.user.password}@wm-registry-0.wm-registry.default.svc.cluster.local:8761/eureka/,http://admin:${spring.security.user.password}@wm-registry-1.wm-registry.default.svc.cluster.local:8761/eureka/
